# El método de k-means

In [6]:
import numpy as np
from scipy.cluster.vq import vq
from scipy.cluster.vq import kmeans

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.05861091, 0.29513038, 0.21233612],
       [0.42755859, 0.07119241, 0.33086683],
       [0.10592624, 0.88895981, 0.97158321],
       [0.82995164, 0.68043986, 0.59322305],
       [0.32470803, 0.73980032, 0.81162107],
       [0.76536501, 0.36831487, 0.11292422],
       [0.04017568, 0.69490884, 0.01648313],
       [0.83600944, 0.18427929, 0.02893966],
       [0.61455279, 0.50379063, 0.98018874],
       [0.84113482, 0.44790702, 0.11641394],
       [0.46077837, 0.23895697, 0.93836663],
       [0.87711063, 0.36016413, 0.74944492],
       [0.38437085, 0.69255798, 0.84229834],
       [0.05497842, 0.72719664, 0.26903675],
       [0.87670659, 0.11900953, 0.08074028],
       [0.22808179, 0.98679088, 0.25135229],
       [0.3253775 , 0.72244212, 0.72014103],
       [0.95030029, 0.41648262, 0.11879733],
       [0.02361418, 0.76816243, 0.75800728],
       [0.33116478, 0.66796381, 0.46660014],
       [0.46084933, 0.67300023, 0.31001503],
       [0.53815993, 0.3341739 , 0.26117628],
       [0.

In [3]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1],data[c2]])
clust_centers

array([[0.46084933, 0.67300023, 0.31001503],
       [0.21683602, 0.23713386, 0.40721718]])

In [5]:
vq(data,clust_centers)

(array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 1, 1, 1, 0, 0]),
 array([0.25763814, 0.27887263, 0.78120508, 0.46529415, 0.52402798,
        0.47371696, 0.51342701, 0.67719763, 0.70808858, 0.48245766,
        0.58449203, 0.68135051, 0.53810499, 0.41151873, 0.72966422,
        0.39507799, 0.43474181, 0.58474587, 0.63318834, 0.20337734,
        0.        , 0.35094933, 0.        , 0.3611311 , 0.38893134,
        0.28232953, 0.55997705, 0.14481961, 0.43161589, 0.64482033]))

In [7]:
kmeans(data,clust_centers)

(array([[0.73447484, 0.32884241, 0.30587782],
        [0.27037263, 0.6069712 , 0.60291531]]),
 0.35592576827019623)

In [9]:
kmeans(data,2)

(array([[0.59938562, 0.36539264, 0.28853658],
        [0.29215967, 0.64466488, 0.70760173]]),
 0.3545359635912436)